// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfZ0krBwMJ0UZPcUqd-5kDRh3gqYLNT0Q',
    appId: '1:377073179829:web:b6464b1caa55f4a1dc72fc',
    messagingSenderId: '377073179829',
    projectId: 'canta-65d33',
    authDomain: 'canta-65d33.firebaseapp.com',
    databaseURL: 'https://canta-65d33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'canta-65d33.appspot.com',
    measurementId: 'G-TWP0FQQWXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-obRQUAREfFDP5GufgX8QyepYHN4DsJQ',
    appId: '1:377073179829:android:bcc0ae78a7316564dc72fc',
    messagingSenderId: '377073179829',
    projectId: 'canta-65d33',
    databaseURL: 'https://canta-65d33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'canta-65d33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQwpWDRUrfOuO6D8RmHSi51Q-9nxR2sBU',
    appId: '1:377073179829:ios:cf81c8d7ce942903dc72fc',
    messagingSenderId: '377073179829',
    projectId: 'canta-65d33',
    databaseURL: 'https://canta-65d33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'canta-65d33.appspot.com',
    iosBundleId: 'com.yemekqr.pakettakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQwpWDRUrfOuO6D8RmHSi51Q-9nxR2sBU',
    appId: '1:377073179829:ios:eccb9eb1f4785c02dc72fc',
    messagingSenderId: '377073179829',
    projectId: 'canta-65d33',
    databaseURL: 'https://canta-65d33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'canta-65d33.appspot.com',
    iosBundleId: 'com.yemekqr.pakettakip.RunnerTests',
  );
}
